development:
  facebook:
    key: '1834464590123904'
    secret: 'f3763707ad9411ac38ab1b58e2b6063c'
  twitter:
    key: 'exK9PzhlwMP9v8nLKJXdoktzc'
    secret: 'jUZXc0ApX7UOQHTT45SKNMZFAXe6a0Bea3rEHnnz1B45vX7sm8'
